export default {
  Default: "",
  Base: "/api",
  Auth: {
    Base: "/auth",
    Login: "/login",
    Register: "/register",
    VerifyToken: "/verify-token",
  },
  Users: {
    Base: "/users",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
    Pagination: "/pagination",
    Search: "/search",
  },
  Tests: {
    Base: "/tests",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
  },
  Roles: {
    Base: "/roles",
    Add: "/add",
  },
  Child: {
    Base: "/childs",
    Add: "/add",
    Update: "/update/:id",
    Delete: "/delete/:id",
    GetAll: "/all",
    GetById: "/get/:id",
  },
  HealthProfile: {
    Base: "/health-profiles",
    Add: "/add",
    GetByID: "/get/:id",
    UpdateById: "/update/:id",
    Search: "/search",
    GetByChildId: "/child/:childId",
  },
  MedicalOrder: {
    Base: "/medical-orders",
    Add: "/add",
    GetById: "/:id",
    UpdateById: "/update/:id",
    DeleteById: "/delete/:id",
    Search: "/search",
    UpdateStatus: "/update-status/:id",
    AddRecord: "/:id/add-record",
    GetRecords: "/:id/records",
    AdditionalDetails: "/:id/additional-details",
  },
} as const;
