export default {
  Default: "",
  Base: "/api",
  Auth: {
    Base: "/auth",
    Login: "/login",
    Register: "/register",
    VerifyToken: "/verify-token",
  },
  Users: {
    Base: "/users",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
    Pagination: "/",
    Search: "/search",
  },
  Tests: {
    Base: "/tests",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
  },
  Roles: {
    Base: "/roles",
    Add: "/add",
  },
  Child: {
    Base: "/childs",
    Add: "/add",
    Update: "/update/:id",
    Delete: "/delete/:id",
    GetAll: "/all",
    GetById: "/get/:id",
  },
  HealthProfile: {
    Base: "/health-profiles",
    Add: "/add",
    GetByID: "/get/:id",
    UpdateById: "/update/:id",
    Search: "/search",
    GetByChildId: "/child/:childId",
  },
  MedicalEvent: {
    Base: "/medical-events",
    GetAll: "/all",
    GetByStudentId: "/student/:studentId",
    GetById: "/get/:id",
    Create: "/create",
    Update: "/update/:id",
    Delete: "/delete/:id",
  },
  MedicalOrder: {
    Base: "/medical-orders",
    Add: "/add",
    GetById: "/:id",
    UpdateById: "/update/:id",
    DeleteById: "/delete/:id",
    Search: "/search",
    UpdateStatus: "/update-status/:id",
    AddRecord: "/:id/add-record",
    GetRecords: "/:id/records",
    AdditionalDetails: "/:id/additional-details",
  },
  VaccinationCampaign: {
    Base: "/vaccination-campaigns",
    Create: "/create",
    Update: "/update/:campaignId",
    GetAll: "/all",
    GetById: "/get/:campaignId",
    AddStudents: "/add-students/:campaignId",
    GetParticipations: "/participations/:campaignId",
    Search: "/search",
  },
  VaccinationParticipation: {
    Base: "/vaccination-participations",
    ParentConsent: "/parent-consent/:participationId",
    RecordVaccination: "/record/:participationId",
    GetParentParticipations: "/parent",
    Search: "/search",
    SearchParent: "/search-parent",
  },
} as const;
